version: "3"
services:
  jenkins:
    image: kinecosystem/jenkins:2.1
    container_name: jenkins
    ports:
       - 5000:5000
       - 8080:8080
    restart: always
    volumes:
      - /jenkins_home:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "3"
